### ISSUE TITLE
Add 'list removed files' option to `sy ls`

### ISSUE THREAD

**Issue by gcala** [syncany/syncany#282]
In current implementation seems impossible to retrieve a list of deleted files with `sy ls`, even when no cleanup is performed, so it becomes tricky/impossible to restore a file by its name.

**Comment by binwiederhier** [comment]
So [this tiny fix](https://github.com/syncany/syncany/commit/f5423bc1bee139c1f7b5ae66ccc0926a5ddb7859) adds a `--deleted` option to the `sy ls` command. As far as I can tell, it should work for all cases except this one: 

```
$ echo 1 > file.txt; sy up
$ rm file1.txt; sy up
$ echo 2 > file.txt; sy up
$ sy ls --deleted
```

In that case, `sy ls --deleted` should show the existing `file.txt` file and the deleted `file.txt` file. But because the return type is a `Map<String, FileVersion>`, it obviously only shows one. Should be fixable.

**Comment by binwiederhier** [comment]
Fixed
