### ISSUE TITLE
Static code analysis: Provide SonarQube Gradle task

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#289]
[SonarQube](http://www.sonarqube.org/) is a pretty awesome static code analysis tool. I'd like to provide our developers with always up-to-date code analysis results (such as [in the example](http://nemo.sonarqube.org/)). 

If someone would like to create a [Gradle task](http://www.gradle.org/docs/current/userguide/sonar_runner_plugin.html) that can be run by Travis with every commit, I'll provide a SonarQube server to report the results to. The JDBC credentials must be read from an environment variable (which can be encrypted with Travis).

Any voluntees? @MrHug?

**Comment by MrHug** [comment]
I can at least take a look at it sure :)
My e-mailadress is in my github profile, so feel free to send it to me there :)

**Comment by binwiederhier** [comment]
I totally forgot about the SonarQube issue, my apologies. I sent the credentials to you via e-mail. You have admin rights for the 'syncany' project. If you need the values of the env variables I've set up for the Gradle task let me know.

**Comment by binwiederhier** [comment]
Friendly bump.

**Comment by binwiederhier** [comment]
On hold for now. No reaction from OP. :-(

**Comment by MrHug** [comment]
Technically speaking you would be the OP, but I'm sorry for not responding. I've been swamped with work for a while now and I keep on snoozing the reminder to take a look at this, simply due to lack of time...

I do have some vaguely related news that might cheer you up though. As you may or may not have noticed Syncany has gotten [another fork](https://github.com/delftswa2014/syncany). Me and three others are currently doing a course on software design called "Software Architecture" and for this course we have to analyze the design of a system. We've chosen to do this for Syncany and the related plug-ins :)

This analysis entails things like a stakeholder analysis, visualizing and describing your architecture and analyzing your current goals and ultimately writing a book chapter about it for a book that is composed by the different chapters (thus different teams) for this course. Whereas this documentation might or might not be of great help to you, one part of the assignment is take a look at some open issues and bring forward pull requests dealing with these issues, so you will probably see some popping up over the next few weeks. 

In return I hope you don't mind if me (or one of the others) drops by in the IRC or on these issues now and again to pester you with some questions related to your designs, visions for Syncany, etc. 

Sorry if this was completely off-topic here, but creating a new issue for it seemed a bit extreme, and dumping all of this in the IRC also seemed a bit out-of-place...
[/wallOfText]

**Comment by binwiederhier** [comment]
Oh boy am I angry that you went OT here. *Kidding*

ad "OP": technically, yes, but ..........

ad "course + lots of Syncany-targeted loved": :+1: :+1: :+1: :+1: :+1: Pim has repeatedly told me about this and I have repeatedly partially forgotten about it. I love talking about Syncany -- especially if it's with intelligent people and about things that might benefit the project! So feel free to drop by and ask away.

**Comment by MrHug** [comment]
Is it possible that the sonarqube server is currently unreachable? I tried accessing http://www.syncany.org:9000/sonarqube (also without the /sonarqube) but I get a 404 ;)

**Comment by binwiederhier** [comment]
I did shut it down as it was not being used; I'll turn it back on for you.

**Comment by MrHug** [comment]
Awesome thanks, though I'm just gonna turn in for today ;)

**Comment by binwiederhier** [comment]
@MrHug Made you a sonar-administrator. You should be able to do everything now. Also: If you edit a post, I don't get e-mails, so it's better to add a new comment if you want to make sure that I see it.
