### ISSUE TITLE
Mac OSX: Native tray icon notifications

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#335]
Like Ubuntu Unity, Mac OSX apparently also has a native notification mechanism. @cr0 started to implement this [on a branch](https://github.com/syncany/syncany-plugin-gui/compare/feature/osx-bwicon?w=1).

**Comment by binwiederhier** [comment]
What you suggested sounds very much exactly like what I described above, right? Meaning: (1) Build by Travis (2) Upload to syncany.org (3) Build Mac GUI (.app.zip) and include the binary.

Go for it if you have the time. And let me know how I can help :smile:

**Comment by cr0** [comment]
Do you have some time today or tomorrow so that we can setup the travis build for the helper utility (including the upload to syncany.org)?

**Comment by binwiederhier** [comment]
Sure I'll be on IRC. Just hit me up when you have a little time.

**Comment by cr0** [comment]
Have a look at [cr0/osx-notifier](https://github.com/cr0/osx-notifier) ![](https://travis-ci.org/cr0/osx-notifier.svg)

**Comment by cr0** [comment]
@binwiederhier I added you as a collaborator in [cr0/osx-notifier](https://github.com/cr0/osx-notifier). Feel free to alter the `.travis.yml` so that the zipped file (`sox-notifier.app.zip`) is uploaded to the Syncany server. We can also move the repo to the syncany organization. This will finish the first todo issue in your list.

**Comment by binwiederhier** [comment]
Looks good so far. For an upload, I'd need a few extra things:

- [ ] Move to syncany org space
- [ ] Rename the Github repo to "syncany-osx-notifier"
- [ ] Rename the .app to something other than "Syncany.app". Shouldn't it be "syncany-osx-notifier.app" or "Syncany OSX Notifier.app" or "Syncany Notifier.app"?
- [ ] Give it version number and name the resulting ZIP file accordingly, e.g. "syncany-osx-notifier_0.4.2-alpha.zip", or something like that (I don't know what the Mac/.app conventions are)
- [ ] I think we should also allow SNAPSHOT releases here. The version naming should be acordingly (e.g. 0.4.2-alpha+SNAPSHOTblabla). 
- [ ] Write a metadata file that contains the version, compile date and a snapshot-flag (or tell me where I can find this information in the ZIP archive); This is needed to keep track of releases/snapshots in the database.

Sorry for all the TODOs, but this time I can't do it on my own :)

**Comment by cr0** [comment]
:rage:

*just kidding*


OS X considers `$1.app` as the app name. Hence, it uses this name to place the notification in the notification center. For instance, Mail.app becomes Mail and Syncany.app becomes Syncany while syncany-osx-notifier.app becomes syncany-osx-notifier which is ugly. To the best of my knowledge this behaviour cannot be changed (c.f. the following figure)
![](http://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/Product_Help/en_US/PUBLIC_USERS/135122/S0402_NotificationCenter.png)
There won't be any problems having two Syncany.app files once we deploy a standalone Mac version of the GUI/Syncany since both apps will have different identifiers (org.syncany.*).

I see your point in having a version identifier. However, imho we don't need snapshots since is much likely that this app won't change often (almost never). Why do you think we need them?

**Comment by binwiederhier** [comment]
ad "Syncany.app": ok then. We'll leave that. 

ad "version": I think a version is always good to have and also necessary for me to manage multiple zip files on the Syncany server. I'm afraid the version and the metainfo file is still necessary. Can't you just write a simple key-value file ("version.properties") and read that during the build process? Then you can also upload that file to the server and I can use it to manage versions.

ad "transfer": I took the ownership away. :) I'll give you temporary ownership so you can transfer the repo.

**Comment by binwiederhier** [comment]
@cr0 I'm taking the ownership again. Please get on IRC and let me know when you have the time to transfer the repo.

**Comment by cr0** [comment]
We could give it another shot tonight or tomorrow. I've incidentally tried to fulfil all your requirements .

**Comment by binwiederhier** [comment]
Sorry I was out. Just ping me on IRC when you are available again. I might be there, I might not. I am moving tomorrow so I might not have Internet right away. Or I might have other things to do :)

**Comment by cr0** [comment]
Ok what's missing is the upload to the Syncany server. Could you alter the travis.yml file and enable the build process? Then I can continue and finish https://github.com/syncany/syncany-plugin-gui/compare/feature/osx-bwicon?w=1

**Comment by binwiederhier** [comment]
Alrighty. It's all set up. Works like a charm. Lots of magic. The logic is the same as with the plugins and the main software: Committing to develop is a [snapshot](https://www.syncany.org/dist/universe/osxnotifier/snapshots/), committing to master is a [release](https://www.syncany.org/dist/universe/osxnotifier/releases/). 

The latest URLs are:
1. https://www.syncany.org/r/syncany-osx-notifier-latest.app.zip (redirects to 3)
2. https://www.syncany.org/r/syncany-osx-notifier-latest-snapshot.app.zip (redirects to 4)
3. https://www.syncany.org/dist/universe/osxnotifier/releases/syncany-osx-notifier-latest.app.zip
4. https://www.syncany.org/dist/universe/osxnotifier/snapshots/syncany-osx-notifier-latest-snapshot.app.zip

Not sure if we want to use these redirect URLs or if you want to keep a direct link+checksum in the code.

**Comment by binwiederhier** [comment]
Done. Good work Christian!
