### ISSUE TITLE
Add PHP backend to default plugins?

### ISSUE THREAD

**Issue by hdijkema** [syncany/syncany#358]
I would appreciate it if the PHP backend that I developed recently would be added to the default plugins of syncany. I would be willing to write documentation for how to use / install it.

**Comment by binwiederhier** [comment]
Thank you very much for your contribution. We appreciate you taking the time to write a plugin and a backend for Syncany. It's good to see that there are ways to make Syncany work even for non-standard cases. 

As of today, the Syncany plugin repository and the API only are tightly coupled together. Plugins maintained by the core team (and part of the [Syncany org space](https://github.com/syncany)) are built by Travis, uploaded to the Syncany server, registered in a database and eventually made visible through the plugin API. This is a process we follow for all the plugins we wrote and, more importantly, for the plugins we also maintain. These are all plugins for standard protocols or services. 

Your PHP/REST-based plugin, however, does not interface with a standard protocol or service, and the code is not owned or maintained by the core team. In its current state, I don't think that we should move the code to the Syncany org space and/or upload the JAR file to the Syncany server, because that would mean we'll have to take care of the code, fix bugs and so on. Right now, we want to concentrate on the **typical/standard use cases and protocols**. 

However, I do think we should allow **third party plugins** and/or a way to list then in the `sy plugin list` command and download them via `sy plugin install <whatever>`. There are multiple ways to do that, and I'd like to discuss this with you guys here if possible. 

**Option 0:** If it's enough for you (which I don't think it is), you can already download plugins from any URL by doing `sy plugin install http://...`. Obviously the plugin is not included in `sy plugin list` though ...

**Option 1:** Open source the Syncany plugin API (see #167) and let you/anyone run their own API server. To include stuff in the `sy (list|install)`, Syncany would query them all and combine the lists. That'd work, but it's quite some effort to actually open source the API and then let you run it. 

**Option 2:** We manually add your plugin to the Syncany API database. We'll add a bogus version number and point to a generic URL. All the details in `<pluginInfo>` would be static (see [details here](https://api.syncany.org/v2/plugins/list?appVersion=0.4.2-alpha)). Would work, but plugin updates are kind of hard to do that way.

**Option 3:** We'll create a tiny web-based interface for the API database to let you edit the plugin versions and download URLs manually. That would definitely work and should be reasonably easy to do. 

What do you think? Opinions?

**Comment by hdijkema** [comment]
I would opt for some kind of plugin repository (option 3?), maybe with a quality rating system. The current standard plugins are good and I don't want to debate your focus on standard use cases and protocols. However, the PHP backend is very easy to implement with any [LAMP](http://en.wikipedia.org/wiki/LAMP_%28software_bundle%29) server and works through the firewall of any workplace where I can plugin my laptop in the BYOD network :-).

**Comment by cr0** [comment]
*We should discuss this in another issue.*

**Comment by binwiederhier** [comment]
@hdijkema We are now able to host third party plugins; if you are still interested to publish your plugin, let me know and I'll give you an API key.

All you have to do is connect your repo to Travis-CI and let Travis build the plugin and upload it to our host. In short: Update your `core/` directory, update your `.travis.yml`, connect your repo to Travis.

Instructions here:
https://github.com/syncany/syncany/wiki/Plugin-development#integrating-the-plugin-in-the-syncany-plugin-api

Also look at the other plugins:
- https://github.com/syncany/syncany-plugin-sftp/blob/b0911cd48cd592a259d0fd631fc49e0a08b7ad4e/.travis.yml#L9
- https://github.com/syncany/syncany-plugin-sftp/blob/b0911cd48cd592a259d0fd631fc49e0a08b7ad4e/.travis.yml#L45

**Comment by binwiederhier** [comment]
I presume this resolves this issue. Please let me know if you have any questions regarding the integration.
