### ISSUE TITLE
gradle(w) on travis is too old

### ISSUE THREAD

**Issue by cr0** [syncany/syncany#359]
At the moment we are using [`gradle(w) 1.11` for our travis builds](https://travis-ci.org/syncany/syncany-plugin-gui/builds/48739613#L1920) which is very old. This is preventing https://github.com/syncany/syncany-plugin-gui/pull/3 from being built successfully. 
This comes up because we now use my gradle-macappbundle-plugin which requires groovy in a more recent version.

Where are we installing gradle 1.11? Is this installed by the wrapper script? According to travis, they provide version 2.0.

Updating gradle should fix this issue, see here: https://github.com/bitsquare/bitsquare/issues/100#issuecomment-57383656.

**Comment by binwiederhier** [comment]
We're using the wrapper from here: https://github.com/syncany/syncany/blob/develop/gradle/wrapper/wrapper.properties. Feel free to update it to the most recent version, but make sure to test all the install tasks. 

Since this is a blocker, feel free to push to `develop` to see if all the tasks still work.

**Comment by binwiederhier** [comment]
To make this work in the syncany-plugin-gui project, you'll have to update the subtree `core/` afterwards, obviously.

**Comment by cr0** [comment]
I assume that everything will blow up :D Let the struggle begin...

**Comment by binwiederhier** [comment]
I don't think so. I think I'm using a different / more up-to-date gradle version locally.
