### ISSUE TITLE
Default .syignore for a repository

### ISSUE THREAD

**Issue by pawi** [syncany/syncany#393]
Creation of a default .syignore for a new repository including:
* desktop.ini
* thumbs.db
* .ds_store

Its safe to assume no one wants these files synced between clients.

**Comment by cr0** [comment]
relates to #66 

Finally, another OS X user who supports the idea to ignore .ds_store files!

**Comment by pawi** [comment]
I think syncing .ds_store could be problematic as such things as window position and size is saved there. Using an iMac 5K ( i wish ;) ) and a MacBook Air afterwards would result in a huge Finder window on the Air (or just a bad user experience). 

It would also reduce the amount of syncing needed for just browsing a folder, as switching the folder view would result in a change of the .ds_store file.

Last point its the default behavior for another popular syncing service.

**Comment by cr0** [comment]
Good point! Perhaps we should follow Dropbox's policy since I assume that they have done extended research considering these points.

**Comment by cr0** [comment]
Could one of you (@binwiederhier or @pimotte) say something about [those edge cases](https://www.dropbox.com/en/help/145) and how Syncany handles them.

**Comment by binwiederhier** [comment]
Sadly enough I cannot say much about edge cases. However, contrary to what my past-self thought, my present-self and hopefully also future-self think that a default .syignore file is a good idea -- meaning that when a repository is created/connected, a .syignore file is created in the repository. 

I actually really like this! Because that means we could also add a nice ignore manager to the GUI (like the one that ownCloud has).

What I would find problematic is to have no .syignore file and just ignore files by default.

:+1: for implementing this.

**Comment by binwiederhier** [comment]
https://github.com/syncany/syncany/commit/3d07fff7f91838a434f1c4ffbdcf4d88b41a9a7f creates a default `.syignore` file with the following content (mostly copied from ownCloud):

```
*.filepart
*~
*.part
*.crdownload
*.unison*
*.csync_timedif.ctmp*
.csync_*
.*.sw?
.*.*sw?
.csync-progressdatabase
.DS_Store
.ds_store
._*
Thumbs.db
thumbs.db
desktop.ini
*.kate-swp
*_conflict-*
*.~*
.TermporaryItems
.Trashes
.DocumentRevisions-V100
.fseventd
.apdisk
~$*
.~lock.*
```
