### ISSUE TITLE
is it possible to disable encryption?

### ISSUE THREAD

**Issue by bachy** [syncany/syncany#420]
Hello,
i am discovering syncany, it looks amazing!
i'm using flat file cms [grav](dk2000) to build a website and i would use sy to deploy contents (md files) automaticaly trough FTP and at the same time sync these contents between several clients.
I used to do that with dropbox but i'm searching for an open source solution.
Also syncany could be very handy with mutualized hosting where we can't install dropbox.
The only thing is that the remote contents are automaticly encrypted, therefor no readable by the cms.
My question is : is there a way to disable the contents encryption ?  
I red all the documentation and searched here for issues but didn't find anything relative to my questions.

**Comment by pimotte** [comment]
It looks to me like you want to have a plaintext format. Even if we disable encryption, the syncany file format splits files into little bits and pieces, so that won't do it. There are two possible solutions:

1. Run a Syncany client on the server as well, and have the repo somewhere on your server outside the cms. This means you have the data twice, but all the syncing will go automatically.
2. Use existing plaintext solutions. I'm thinking something involving cron and a small script which syncs over ftp should do the trick. Maybe rsync is suitable as well?

**Comment by binwiederhier** [comment]
We should add this to the FAQ and move the FAQ to the user guide.

**Comment by cr0** [comment]
We should add some figures showing how a sync (down & up) happens. Some executive slides or so....

**Comment by binwiederhier** [comment]
@cr0 
This is a set of slides that I presented at Datto and Deutsche Bank (in rather technical circles though). I'm not sure if any of the figures is executive compatible though :smile::

https://github.com/syncany/syncany-assets/blob/de9301d28164b766cfcee7b2e4f4b2356df06904/documentation/other/Syncany%20Presentation.pdf

**Comment by cr0** [comment]
The images from slide 11 are a perfect answer to this issue. The rest... I agree that's a little bit too technical for some users.

**Comment by binwiederhier** [comment]
Seems like someone doesn't know our user guide :) Because those two have been taken from there http://syncany.readthedocs.org/en/latest/concepts.html#minimizing-remote-disk-space-through-deduplication
