### ISSUE TITLE
 Amazon Cloud Drive plugin

### ISSUE THREAD

**Issue by l3iggs** [syncany/syncany#421]
Amazon just announced Cloud Drive with unlimited storage for 59.99 USD per year making it the value leader among (consumer?) cloud storage solutions. It would be great to have a plugin that would allow syncany to talk to it.

**Comment by cr0** [comment]
I've to admit that this is a great deal and we too see a growing demand to use that as a Syncany backend.

Amazon provides an [https://developer.amazon.com/public/apis/experience/cloud-drive/content/getting-started](API). However, there seems to be no Java SDK available at the moment, especially for none for the [Nodes API](https://developer.amazon.com/public/apis/experience/cloud-drive/content/nodes). This complicates things a lot. Please correct me if I'm wrong.

**Comment by l3iggs** [comment]
Their API is REST-based. So maybe something like this:
http://crest.codegist.org/
or this:
https://jax-rs-spec.java.net/
is helpful here.

**Comment by cr0** [comment]
FYI: I've started to work on this issue. Perhaps we might outsource some kind of minimal cloud drive sdk. However, this might still take some time, so don't be impatient.

**Comment by sanjay** [comment]
Is the work being posted on Github somewhere?  I'm a hack as a coder but I'd be willing to dive into this to help out and get the plugin up and running.  And yeah, I'm a Prime member too - that Flickr plugin looks might appealing right about now.  :-)

**Comment by cr0** [comment]
Nice to see your interest. The code isn't up yet, but as soon as something is working, I'll create a repo somewhere.

**Comment by dmexs** [comment]
cr0, was looking at throwing together my own plugin. It seems that one of the first barriers to implementing the Cloud Drive API as it stands is the authentication mechanism? Using Login with Amazon you have to have the user visit https://www.amazon.com/ap/oa and then redirect with an authentication code in the URI. Seems like a lot of hoops to jump through for a cli-based app?

**Comment by binwiederhier** [comment]
@dmexs We have a mechanism in place to handle the OAuth flow, but it might just work for Amazon Login as well. You can see how this works in the Flickr or Dropbox plugin. It works for the CLI and the GUI, see for example here: https://www.youtube.com/watch?v=zdUucWr3wKA. For the CLI, it looks like this:

```
$ sy init 
Choose a storage plugin. Available plugins are: dropbox, flickr, ftp, local, s3, sftp, webdav
Plugin: dropbox

Connection details for dropbox connection:

This plugin needs you to authenticate your account so that Syncany can access it.
Please navigate to the URL below and enter the token:

  https://www.dropbox.com/1/oauth2/authorize?locale=en&client_id=dlg8wdfpf3xa5jv&response_type=code

- Token (paste from URL): 
...
```

As a plugin developer, all you have to do is [this](https://github.com/syncany/syncany-plugin-dropbox/blob/develop/src/main/java/org/syncany/plugins/dropbox/DropboxTransferSettings.java#L39) and [this](https://github.com/syncany/syncany-plugin-dropbox/blob/develop/src/main/java/org/syncany/plugins/dropbox/DropboxTransferSettings.java#L60).

@dmexs Just out of curiosity, why do you think that Syncany is CLI-based only? I'm asking because this happens from time to time, and people are surprised to see that there is a GUI. Did you not scroll down on the main website, or did you just come here through GitHub? I get the feeling we should feature the GUI more prominently.

**Comment by dmexs** [comment]
@binwiederhier thanks for the info. This should be helpful to play around with.

As for the GUI, I knew there was a GUI based on the images on the bottom of the app website. I guess I was focusing on my particular use case which is on a headless linux server.

**Comment by binwiederhier** [comment]
ad "GUI": Thanks!

**Comment by cr0** [comment]
First part of the Amazon cloud drive plugin is waiting as a pull request (#426).

**Comment by l3iggs** [comment]
very cool!

**Comment by sanjay** [comment]
Any status on this?  I'm itching to try this out.

**Comment by cr0** [comment]
Thank you for your interest. Please see #444 for further status updates, I'll plan to work on this this evening!

**Comment by binwiederhier** [comment]
@cr0 Good stuff :)
