### ISSUE TITLE
Usings plugins for "localdir"

### ISSUE THREAD

**Issue by betaglop** [syncany/syncany#481]
Would it be possible / difficult to use plugins to access the "localdir" ? The idea is to be able to consider a distant FTP/WebDAV/etc. folder as the place to "sy down" / "sy up" data from the repository.

This can be a request of feature as it can be only a request of information for a further development.
Thanks in advance.

**Comment by pimotte** [comment]
Is there any reason why you can't run Syncany on the server? If you can do that, that would be the supported method.

**Comment by betaglop** [comment]
yes we thank about this... but no:
if we do that we should add a syncany repository + daemon by user on the server, because every user has its own

**Comment by pimotte** [comment]
While not really a supported manner of usage, you could technically init using a local Syncany, edit all the encrypted variables in the config.xml to be unencrypted and then use a syncany daemon on the server to do the syncing, which means decentralization of configuration, but not of confidentiality.

The usage you have described in the other issue (mounting with fuse-drivers) would be the way to go, since having Syncany do this communication to the server is exactly the opposite of what Syncany is trying to do, and hence outside the scope of the project. Since using Syncany in the manner is not unsupported per se, it does run into some issues because of the high-latency nature of the filesystem, but your other issue perfectly describes those.

Therefore I'm going to close this issue and keep the other one open. Feel free to leave message/reopen this if you have a good reason to:)
