### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by HLFH** [syncany/syncany#525]
Hi,

Could we get an official systemd file for syncany?
At the moment, it seems [quite complicated to automatically use syncany](http://syncany.readthedocs.org/en/latest/getting_started.html#automatically-syncing-files). 
I want to automatically backup some files and folders from my ArchLinux server to a remote FTP server. But it [does not seem that a systemd file exists](https://aur.archlinux.org/packages/syncany/).

Thanks in advance,
HLFH

**Comment by pimotte** [comment]
https://github.com/syncany/syncany/commit/194955dd46925548fef8339f11cbbc41e0867dd0 provides a user-level systemd file. 

Since it's not included in the release from yesterday, I can't put it in the PKGBUILD just yet. Feel free to download the files yourself and add them in the PKGBUILD, or use the syncany-git AUR package I have reinstated.

This is the first time I've written one of these, so if you have any feedback, feel free to let me know or PR.
