### ISSUE TITLE
Adjust crypto concept & implementation (no nested ciphers)

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#59]
Due to security concerns raised by Internetland, crypto students and even a few well-respected cryptographers, nesting ciphers could be vulnerable to different kinds of attacks (meet-in-the-middle, etc.)

**The crypto concept and implementation has to be adjusted accordingly.**

Related:
- Issue https://github.com/binwiederhier/syncany/issues/28
- http://crypto.stackexchange.com/questions/5827/can-a-nested-block-cipher-avoid-the-meet-in-the-middle-attack-by-using-a-secret
- http://crypto.stackexchange.com/questions/1737/can-nesting-different-ciphers-with-different-keys-ever-decrease-security

**Comment by Asherehsa** [comment]
I'm using Syncany on 4 different computers and one is coming up with the error you posted (the others seem to be working fine): Error: Downloading multichunk 4/268 ...Error: Decryption/extraction of multichunk c425608908e42d2d15d87377cb2070088764d505 failed. The multichunk might have been tampered with!
I'm sorry if this is the wrong place for feedback but are there any tips for resolving the error?

**Comment by pimotte** [comment]
After talking to my crypto prof, it looks like the crypto concept is solid. There is a little bit of uncertainty with regards to the nesting concept, but since this is no longer a default I don't think this is a problem.

The suggestion he had is that the weakest part is the user password and it might be worthwhile to piggyback on existing tools/infrastructure (say certificates) to generate strong passwords in a pseudo-friendly format. The other part is that implementation flaws can always mess things up. Given that we use BouncyCastle I'm not particularly worried, but this is something to consider.

My suggestion is to make a seperate issue for certificate-thing this if we decide to want it and close this issue.

**Comment by binwiederhier** [comment]
Well that sounds very good. Judging from the amount of people that have looked at the concept and the feedback, I think we've done a good job here. As you said, implementation can always be an issue ... Not sure if we can ever be sure that it's secure. What do you suggest? Close this issue for now?

Can you elaborate on the "piggyback on existing tools/infrastructure (say certificates) to generate strong passwords in a pseudo-friendly format"? I have no idea what that means. Did you mean using public key cryptography instead of passwords?

**Comment by pimotte** [comment]
It just means using a key-file of some sort, certificates are just a way to standardize them. This enables users to easily use a very strong password, without having to remember a 20 character random string.

Using pubkey crypto to exchange a strong repo key also sounds nice, but I think that would be something that could be provided by a provider, rather than have it built into syncany.

**Comment by binwiederhier** [comment]
Having the nested file format is not harmful. The default cipher suite has been updated to AES_128_GCM only. Manually changing to multiple ciphers is still possible:

https://github.com/syncany/syncany/blob/develop/syncany-lib/src/main/java/org/syncany/crypto/CipherSpecs.java#L64
